"""fixes bigint to int for moons count

Revision ID: dba44d5ba1cd
Revises: 5c856d05c482
Create Date: 2025-04-24 11:35:18.214380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba44d5ba1cd'
down_revision = '5c856d05c482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('moons_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('moons_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
